export const devConfig = {
  CATEGORIES_NUMBER: 5,
  MAX_LIKES_NUMBER: 2000000,
  DESTRUCTION_NUMBER_COUNT: 100,
  SHORT_DESCRIPTION_WORDS_COUNT: 10,
  STORIES_PER_CATEGORY: 20,
  CATEGORIES: [
    'Politics',
    'Health',
    'Sport',
    'Gaming',
    'World',
    'Russia Ukraine War',
    'Coronavirus',
    'Economics',
  ],
  // [
  //   { name: 'Politics', abr: 'politics' },
  //   { name: 'Health', abr: 'health' },
  //   { name: 'Sport', abr: 'sport' },
  //   { name: 'Gaming', abr: 'gaming' },
  //   { name: 'World', abr: 'world' },
  //   { name: 'Russia Ukraine War', abr: 'russiaUkraineWar' },
  //   { name: 'Coronavirus', abr: 'coronavirus' },
  //   { name: 'Economics', abr: 'economics' },
  // ],
};
